name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 🔹 1) Job de Testes
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Rodar testes
        run: |
          pytest --junitxml=report.xml --maxfail=1 --disable-warnings -q

      - name: Salvar relatório de testes
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-testes
          path: report.xml

  # 🔹 2) Job de Build (roda em paralelo)
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Empacotar projeto
        run: |
          python setup.py sdist bdist_wheel

      - name: Salvar pacote
        uses: actions/upload-artifact@v3
        with:
          name: pacote
          path: dist/

  # 🔹 3) Job de Notificação (em paralelo)
  notify:
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: sudo apt-get install -y mailutils

      - name: Enviar e-mail
        env:
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: |
          echo "Pipeline executado com sucesso!" | mail -s "Notificação Pipeline" $EMAIL_DESTINO
